version: '3.7'

services:
  mica:
    image: obiba/mica:snapshot
    ports:
    - "8845:8445"
    - "8882:8082"
    links:
    - mongo
    - opal
    - agate
    environment:
    - MICA_ADMINISTRATOR_PASSWORD=password
    - MICA_ANONYMOUS_PASSWORD=password
    - MONGO_PORT_27017_TCP_ADDR=172.20.128.10
    - MONGO_PORT_27017_TCP_PORT=27017
    - AGATE_PORT_8444_TCP_ADDR=172.20.128.13
    - AGATE_PORT_8444_TCP_PORT=8444
    - OPAL_PORT_8443_TCP_ADDR=172.20.128.11
    - OPAL_PORT_8443_TCP_PORT=8443
    volumes:
    - /tmp/mica:/srv
    networks:
      obiba_network:
        ipv4_address: 172.20.128.12
  opal:
    image: obiba/opal:snapshot
    ports:
    - "8843:8443"
    - "8880:8080"
    links:
    - mongo
    environment:
    - OPAL_ADMINISTRATOR_PASSWORD=password
    - MONGO_PORT_27017_TCP_ADDR=172.20.128.10
    - MONGO_PORT_27017_TCP_PORT=27017
    - AGATE_PORT_8444_TCP_ADDR=172.20.128.13
    - AGATE_PORT_8444_TCP_PORT=8444
    volumes:
    - /tmp/opal:/srv
    networks:
      obiba_network:
        ipv4_address: 172.20.128.11
  agate:
    image: obiba/agate:snapshot
    ports:
    - "8844:8444"
    - "8881:8081"
    links:
    - mongo
    environment:
    - AGATE_ADMINISTRATOR_PASSWORD=password
    - MONGO_PORT_27017_TCP_ADDR=172.20.128.10
    - MONGO_PORT_27017_TCP_PORT=27017
    volumes:
    - /tmp/agate:/srv
    networks:
      obiba_network:
        ipv4_address: 172.20.128.13
  mongo:
    image: mongo:4.0
    volumes:
      - /tmp/mongo_db:/data/db
      - /tmp/mongo_configdb:/data/configdb
    networks:
      obiba_network:
        ipv4_address: 172.20.128.10
networks:
  obiba_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.128.1/24
